version: "3.9"

services:
  app:
    build: .
    container_name: document_chatbot
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit (fixed port)
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatdb
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: ankane/pgvector:latest  # Use latest version
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: auto-enable extension
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: